import React from 'react';
import Head from 'next/head';
import Image from 'next/image';

function Signin() {
  return (
    <div>
         <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Image
        src="https://rb.gy/y9mwtb"
        height={250}
        width={600}
        objectFit="contain"
        className="animate-pulse"
      />
    </div>
  )
}

export default Signin;