import { useSession } from 'next-auth/react'
import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import Dashboard from '../components/Dashboard'
import Loader from '../components/Loader'
import styles from '../styles/Home.module.css'

export default function Home() {
  const router = useRouter();
  const {data: session, status} = useSession({
    onUnauthenticated() {
      router.push("/auth/signin")
    }
  });
  if (status ==="loading"){
    return <Loader/>
  }
  console.log(session)

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Dashboard/>
      </div>
    </div>
  )
}
